upload_max_filesize = 3000M
post_max_size = 3000M
memory_limit = 256M
max_execution_time = 300
max_input_time = 300
max_input_vars = 10000
max_file_uploads = 20
max_upload_filesize = 3000M
extension=zip
